$schema: https://azuremlschemas.azureedge.net/latest/batchDeployment.schema.json
name: hello-batch-deployment
endpoint_name: hello-batch-endpoint
compute: azureml:cpu-cluster  # Ensure this compute target exists
environment: azureml:hello-env@latest
code_configuration:
  code: .
  scoring_script: score.py
inputs:
  input_data:
    type: uri_file
model:
  path: .

# Optional recommended fields:
# mini_batch_size: 10
# max_concurrency_per_instance: 1
# resources:
#   instance_count: 2
