$schema: https://azuremlschemas.azureedge.net/latest/batchDeployment.schema.json
name: cv-batch-deployment
endpoint_name: cv-batch-endpoint
compute: cpu-cluster
component: pipeline.yaml

model:
  path: .