$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: cv_model_inference
display_name: CV Model Inference
version: 2
type: command
inputs:
  input_data_path:
    type: uri_file
outputs:
  output_dir:
    type: uri_folder
code: ../src
environment: azureml:env-inference@latest
command: >
  python src/components/cv_model_inference.py
  --input_data_path ${{inputs.input_data_path}}
  --output_dir ${{outputs.output_dir}}