$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: cv_model_inference
display_name: CV Model Inference
version: 22
type: command
inputs:
  input_dir:
    type: uri_folder
outputs:
  output_dir:
    type: uri_folder
code: ../src
environment: azureml:env-inference@latest
command: >
  python components/cv_model_inference.py
  --input_dir ${{inputs.input_dir}}
  --output_dir ${{outputs.output_dir}}