$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: cv_model_inference
display_name: CV Model Inference
version: 26
type: command
inputs:
  input_url:
    type: uri_folder
outputs:
  output_url:
    type: uri_folder
code: ../src
environment: azureml:env-inference@latest
command: >
  python components/cv_model_inference.py
  --input_url ${{inputs.input_url}}
  --output_url ${{outputs.output_url}}