$schema: https://azuremlschemas.azureedge.net/latest/PipelineJob.schema.json
type: pipeline
name: cv_pipeline
display_name: CV Pipeline
version: 7

inputs:
  input_dir:
    type: uri_folder
    description: "Input data directory"

outputs:
  validation_output:
    type: uri_folder
    description: "Validation output directory"
  inference_output:
    type: uri_folder
    description: "Inference output directory"

jobs:
  validation_step:
    type: command
    component: azureml:cv_model_validate@latest
    inputs:
      input_dir: ${{ parent.inputs.input_dir }}
    outputs:
      validation_result: ${{ parent.outputs.validation_output }}

  inference_step:
    type: command
    component: azureml:cv_model_inference@latest
    inputs:
      input_data_path: ${{ parent.jobs.validation_step.outputs.validation_result }}
    outputs:
      output_dir: ${{ parent.outputs.inference_output }}