$schema: https://azuremlschemas.azureedge.net/latest/PipelineJob.schema.json
type: pipeline
name: cv_pipeline
display_name: CV Pipeline
experiment_name: cv_experiment

jobs:
  validation_step:
    type: command
    component: azureml:cv_model_validate@latest
    inputs:
      input_dir:
        mode: ro_mount  # Read-only mount
        path: azureml://datastores/workspaceblobstore/paths/data/input_data/
  inference_step:
    type: command
    component: azureml:cv_model_inference@latest
    inputs:
      input_data_path: ${{jobs.validation_step.outputs.output_file}}