$schema: https://azuremlschemas.azureedge.net/latest/pipelineDeployment.schema.json

name: cv-deployment-gitaction
endpoint_name: cv-batch-endpoint

type: pipeline  # Indicates we're creating a pipeline deployment

jobs:
  run_pipeline_component:
    type: pipeline
      component: azureml:cv_pipeline@latest

    # inputs:
    #   input_data: azureml://datastores/myds/paths/my_input_folder
    # outputs:
    #   output_data: azureml://datastores/myds/paths/my_output_folder
