$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: cv_model_validate
display_name: CV Model Validation
version: 31
type: command
inputs:
  input_url:
    type: uri_folder
outputs:
  output_url:
    type: uri_folder
code: ../../src
environment: azureml:env-validate@latest
command: >
  python components/cv_model_validate.py
  --input_url ${{inputs.input_url}}
  --output_url ${{outputs.output_url}}