name: Deploy Batch Endpoint on Merge to Qua

on:
  push:
    branches: [ qua ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install Azure ML CLI extension
        run: az extension add -n ml --yes

      - name: Create or update batch endpoint
        run: |
          az ml batch-endpoint create --file endpoint.yaml \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }}

      - name: Create or update batch deployment
        run: |
          az ml batch-deployment create --file deployment.yaml \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }}

      - name: Set default deployment
        run: |
          az ml batch-endpoint update --name hello-batch-endpoint \
            --set defaults.deployment_name=hello-batch-deployment \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }}
